### ISSUE TITLE
Parse half the demo

### ISSUE THREAD

**Issue by NLPiation** [pnxenopoulos/csgo#11] opened 2021-03-28 01:44 UTC
**Describe the bug**
I tried to parse a demo from HLTV, but it only parses half the match. (until 6-6 score) I also checked the demo on the CSGO but could not find anything odd.
Also, it seems to work fine on other demo files, and there are no errors in the log file.

**To Reproduce**
The match page on HLTV if you want to reproduce.
https://www.hltv.org/matches/2347482/dignitas-vs-mad-lions-nordic-masters-spring-2021-blast-premier-qualifier

I checked another match demo from the same event: https://www.hltv.org/matches/2347483/singularity-vs-ence-nordic-masters-spring-2021-blast-premier-qualifier
It is not complete as well; the code does not parse the last round. (Maybe something wrong with the way that the event is recording the demos?)

**Desktop (please complete the following information):**
 - OS: MacOS 11.2
 - Python 3 / jupyter

**Comment by pnxenopoulos** [comment] 2021-03-28 09:54
Hey @NLPiation, thanks for checking out the package. I was able to reproduce the error locally for both demofiles. For the second match, I found the parser was actually missing two rounds (right after halftime and right before the end). This error has come up occasionally during testing over the past few months.

I've got a paper deadline on Wednesday this week, but I will look into this after Wednesday. I suspect it will not take too long, and I should have this resolved by end of week. It _could_ be a problem with this event, but it's more likely a problem with the parser.

**Comment by NLPiation** [comment] 2021-03-28 17:37
Thanks. Appreciate the fast response.

**Comment by pnxenopoulos** [comment] 2021-04-06 03:05
Hi @NLPiation, I believe the issue is fixed. I parsed locally and got 28 rounds for the Dignitas game. Let me know if you are able to parse with the new code (be sure to `git pull`).

**Comment by NLPiation** [comment] 2021-04-06 03:09
Great @pnxenopoulos, I will give it a try tomorrow and let you know.

**Comment by pnxenopoulos** [comment] 2021-04-06 14:20
@NLPiation looking into this now. Should have a fix in a few hours.

**Comment by pnxenopoulos** [comment] 2021-04-06 14:51
@NLPiation unfortunately, this demo is not sending out "Round End" events in the demofile for the round right after halftime nor the one right before the map ends. This can occasionally happen with some demos. I don't quite have a solution for it, as it will require much more investigation, and potentially creating some drawn-out fuzzy logic to infer round ends. My hope is that the  [markuswa project](https://github.com/markus-wa/demoinfocs-golang) will come to accommodate these issues in the future. For now, I will close the issue here, since we fixed the initial demofile. The second one requires a more long-term solution.

**Closed by pnxenopoulos** 2021-04-06 14:51 UTC
Labels: Bug, Medium Priority

**Comment by pnxenopoulos** [comment] 2021-04-14 03:46
Hey @NLPiation, I made a substantial update to the parser. I checked both demofiles and they parsed correctly on my local machine. If you run into any other issues, let me know.
