### ISSUE TITLE
Bad round included after using clean_rounds method

### ISSUE THREAD

**Issue by kenmareirl** [pnxenopoulos/csgo#79] opened 2021-12-15 09:51 UTC
**Describe the bug**
I parsed and used after the clean_rounds method. It seems to have a problem with a round included (which doesn't have to).

**To Reproduce**
1. Parse the vertigo dem of this match https://www.hltv.org/matches/2353164/vitality-vs-g2-iem-winter-2021
2. Open the JSON generated
3. Check roundNum 1 which seems to be the bad one, because the score is the same that roundNum 2

**Expected behavior**
JSON file without this bad round

**Screenshots**
![Round_1](https://user-images.githubusercontent.com/92644057/146163676-668a5fb7-6fd7-45cf-bba2-349b83fcd415.png)
![Round_2](https://user-images.githubusercontent.com/92644057/146163684-bfde0ca7-d86e-47b0-9ebc-a3518d978182.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [N/A]
 - Version [N/A]

**Smartphone (please complete the following information):**
 - Device: [N/A]
 - OS: [N/A]
 - Browser [N/A]
 - Version [N/A]

**Additional context**
N/A

**Comment by pnxenopoulos** [comment] 2021-12-17 05:00
Thanks for the report. I believe the issue is that the first round is certainly a warmup when it is not listed as such. 

One potential solution here is to add a filter to identify these "bad" rounds post-parsing. For example, we know a spend of 200850 (the ct spend in round 1) is not possible in a comp round.

**Comment by pnxenopoulos** [comment] 2021-12-23 19:25
Should be fixed in #85

**Closed by pnxenopoulos** 2021-12-23 19:25 UTC
Labels: Bug, Medium Priority, Demo Parsing Failed
