### ISSUE TITLE
Error when parsing some demos

### ISSUE THREAD

**Issue by askvrtsv** [pnxenopoulos/csgo#9] opened 2021-02-24 09:37 UTC
An error occurs when parsing the demo from https://www.hltv.org/matches/2346594/secret-club-vs-triumph-esea-winter-cash-cup-5-north-america. The error occurs only for `secret-club-vs-triumph-m2-inferno.dem` demo.

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Volumes/GREY/code/csgo/parse_csgo.py", line 19, in <module>
    main()
  File "/Volumes/GREY/code/csgo/parse_csgo.py", line 14, in main
    data = demo_parser._parse_demo()
  File "/Volumes/GREY/code/csgo/csgo/parser/demoparser.py", line 117, in _parse_demo
    self.output_file = output[0]
IndexError: list index out of range
```

The parser log contains the following entries:
```
INFO: 2021/02/24 11:52:36 parse_demo.go:631: Started demoparser
INFO: 2021/02/24 11:52:36 parse_demo.go:655: Parsed arguments, reading in /Volumes/GREY/code/csgo/data/secret-club-vs-triumph-m2-inferno.dem and a parse rate of 8 
INFO: 2021/02/24 11:52:36 parse_demo.go:677: Parsed demo header and mesh for map de_inferno 
INFO: 2021/02/24 11:52:36 parse_demo.go:710: Demo is of type GOTV Demo with tickrate 128 
INFO: 2021/02/24 11:52:36 parse_demo.go:711: Demo name is secret-club-vs-triumph-m2-inferno from /Volumes/GREY/code/csgo/data/secret-club-vs-triumph-m2-inferno.dem
INFO: 2021/02/24 11:52:36 parse_demo.go:712: Registering event handlers, parsing demo
ERROR: 2021/02/24 11:52:43 parse_demo.go:1700: DEMO STREAM ERROR
WARNING: 2021/02/24 11:52:43 parse_demo.go:1701: Demo stream errors can still write output, check for JSON file
ERROR: 2021/02/24 11:52:43 parse_demo.go:1702: runtime error: index out of range [-1]
stacktrace:
goroutine 6 [running]:
runtime/debug.Stack(0x203000, 0x203000, 0x1f149f0)
	/usr/local/Cellar/go/1.15.8/libexec/src/runtime/debug/stack.go:24 +0x9f
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.NewParserWithConfig.func1(0x14be200, 0xc0028073e0)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.5.0/pkg/demoinfocs/parser.go:316 +0x2f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1(0xc00005e2a0)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:190 +0x6b
panic(0x14be200, 0xc0028073e0)
	/usr/local/Cellar/go/1.15.8/libexec/src/runtime/panic.go:969 +0x1b9
github.com/markus-wa/godispatch.callConsumerCode.func1()
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:120 +0x88
panic(0x14be200, 0xc0028073d0)
	/usr/local/Cellar/go/1.15.8/libexec/src/runtime/panic.go:969 +0x1b9
github.com/markus-wa/godispatch.callConsumerCode.func1()
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:120 +0x88
panic(0x14d4ea0, 0xc003ec6a80)
	/usr/local/Cellar/go/1.15.8/libexec/src/runtime/panic.go:969 +0x1b9
main.main.func13()
	/Volumes/GREY/code/csgo/csgo/parser/parse_demo.go:1592 +0x168e
reflect.Value.call(0x147b440, 0xc00008c060, 0x13, 0x151a4a6, 0x4, 0xc0005e5ae0, 0x1, 0x1, 0x14bcb80, 0xc003c6efd0, ...)
	/usr/local/Cellar/go/1.15.8/libexec/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0x147b440, 0xc00008c060, 0x13, 0xc0005e5ae0, 0x1, 0x1, 0xc001efe948, 0x70decf1d78da4601, 0x70000000013fcf25)
	/usr/local/Cellar/go/1.15.8/libexec/src/reflect/value.go:337 +0xb9
github.com/markus-wa/godispatch.callConsumerCode(0x147b440, 0xc00008c060, 0x13, 0xc0005e5ae0, 0x1, 0x1)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:123 +0x8c
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc00005e300, 0x149ab00, 0x18d5bd0)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:109 +0x252
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.(*parser).handleFrameParsed(0xc000001200, 0x18d5bd0)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.5.0/pkg/demoinfocs/parsing.go:374 +0xa5
reflect.Value.call(0x147adc0, 0xc000052660, 0x13, 0x151a4a6, 0x4, 0xc0005e5f28, 0x1, 0x1, 0xc0005e5e30, 0x0, ...)
	/usr/local/Cellar/go/1.15.8/libexec/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0x147adc0, 0xc000052660, 0x13, 0xc0005e5f28, 0x1, 0x1, 0xc0000211e8, 0x836af79e65938001, 0x830000000105f940)
	/usr/local/Cellar/go/1.15.8/libexec/src/reflect/value.go:337 +0xb9
github.com/markus-wa/godispatch.callConsumerCode(0x147adc0, 0xc000052660, 0x13, 0xc0005e5f28, 0x1, 0x1)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:123 +0x8c
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc00005e2a0, 0x1469460, 0x18d5bd0)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:109 +0x252
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc00005e2a0, 0x1469460, 0x18d5bd0)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:195 +0x66
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc00005e2a0, 0xc00005e360)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:171 +0xf4
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:157 +0x148

INFO: 2021/02/24 11:52:43 parse_demo.go:1610: Parsed %s /Volumes/GREY/code/csgo/data/secret-club-vs-triumph-m2-inferno.dem
```

The bug appears on macOS 11.2.1, Python 3.9.1, Go 1.15.8.

**Comment by pnxenopoulos** [comment] 2021-02-24 15:56
Hi @askvrtsv, thanks for checking out the `csgo` library. I was able to reproduce the error. I believe I fixed it with the most recent release. Please download the latest version of the `csgo` library and install it. Let me know if the issue persists.

**Comment by askvrtsv** [comment] 2021-02-25 07:27
Thanks for the quick fix. Now this demo parses perfectly.

Thanks again for your great work!

**Comment by askvrtsv** [comment] 2021-02-25 07:31
But I ran into another demo that causes a similar error.

When parsing the demo of this match https://www.hltv.org/matches/2346640/rush-vs-durany-dreamhack-open-march-2021-south-america-open-qualifier-1 (direct link to the demo: https://www.hltv.org/download/demo/62438) it gives the same error in Python.

Here is the parser log:

```
INFO: 2021/02/25 10:24:21 parse_demo.go:631: Started demoparser
INFO: 2021/02/25 10:24:21 parse_demo.go:655: Parsed arguments, reading in /Volumes/GREY/code/csgo/data/rush-vs-durany-dust2.dem and a parse rate of 64 
INFO: 2021/02/25 10:24:21 parse_demo.go:677: Parsed demo header and mesh for map de_dust2 
INFO: 2021/02/25 10:24:21 parse_demo.go:710: Demo is of type GOTV Demo with tickrate 128 
INFO: 2021/02/25 10:24:21 parse_demo.go:711: Demo name is rush-vs-durany-dust2 from /Volumes/GREY/code/csgo/data/rush-vs-durany-dust2.dem
INFO: 2021/02/25 10:24:21 parse_demo.go:712: Registering event handlers, parsing demo
ERROR: 2021/02/25 10:24:21 parse_demo.go:1719: DEMO STREAM ERROR
WARNING: 2021/02/25 10:24:21 parse_demo.go:1720: Demo stream errors can still write output, check for JSON file
ERROR: 2021/02/25 10:24:21 parse_demo.go:1721: runtime error: invalid memory address or nil pointer dereference
stacktrace:
goroutine 18 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.8/libexec/src/runtime/debug/stack.go:24 +0x9f
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.NewParserWithConfig.func1(0x14be680, 0xc0003d8900)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.5.0/pkg/demoinfocs/parser.go:316 +0x2f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1(0xc0000b0240)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:190 +0x6b
panic(0x14be680, 0xc0003d8900)
	/usr/local/Cellar/go/1.15.8/libexec/src/runtime/panic.go:969 +0x1b9
github.com/markus-wa/godispatch.callConsumerCode.func1()
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:120 +0x88
panic(0x14be680, 0xc0003d88f0)
	/usr/local/Cellar/go/1.15.8/libexec/src/runtime/panic.go:969 +0x1b9
github.com/markus-wa/godispatch.callConsumerCode.func1()
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:120 +0x88
panic(0x149b640, 0x189a7c0)
	/usr/local/Cellar/go/1.15.8/libexec/src/runtime/panic.go:969 +0x1b9
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs/common.(*TeamState).ClanName(...)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.5.0/pkg/demoinfocs/common/common.go:143
main.main.func10(0x9efa398, 0xc000626180)
	/Volumes/GREY/code/csgo/csgo/parser/parse_demo.go:1147 +0x2c8
reflect.Value.call(0x147b900, 0xc00068c100, 0x13, 0x151a926, 0x4, 0xc001263978, 0x1, 0x1, 0xc0000fde60, 0x0, ...)
	/usr/local/Cellar/go/1.15.8/libexec/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0x147b900, 0xc00068c100, 0x13, 0xc001263978, 0x1, 0x1, 0xc0000aab78, 0xce12cfc0fccf2c01, 0xce00000005010106)
	/usr/local/Cellar/go/1.15.8/libexec/src/reflect/value.go:337 +0xb9
github.com/markus-wa/godispatch.callConsumerCode(0x147b900, 0xc00068c100, 0x13, 0xc001263978, 0x1, 0x1)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:123 +0x8c
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0000b02a0, 0x14b4e00, 0xc000626180)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:109 +0x252
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.gameEventHandler.dispatch(...)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.5.0/pkg/demoinfocs/game_events.go:60
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.gameEventHandler.smokeGrenadeExpired(0xc000082480, 0x0, 0xc000091140, 0xc000091170, 0xc001bd9290)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.5.0/pkg/demoinfocs/game_events.go:455 +0x152
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.(*parser).handleGameEvent(0xc000082480, 0xc000553ac0)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.5.0/pkg/demoinfocs/game_events.go:39 +0x182
reflect.Value.call(0x147b300, 0xc00008e600, 0x13, 0x151a926, 0x4, 0xc001263f28, 0x1, 0x1, 0xc0000fcc60, 0x0, ...)
	/usr/local/Cellar/go/1.15.8/libexec/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0x147b300, 0xc00008e600, 0x13, 0xc001263f28, 0x1, 0x1, 0xc0000aaf38, 0x9182509f8072dc01, 0x9100000008010101)
	/usr/local/Cellar/go/1.15.8/libexec/src/reflect/value.go:337 +0xb9
github.com/markus-wa/godispatch.callConsumerCode(0x147b300, 0xc00008e600, 0x13, 0xc001263f28, 0x1, 0x1)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:123 +0x8c
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0000b0240, 0x14fc040, 0xc000553ac0)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:109 +0x252
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc0000b0240, 0x14fc040, 0xc000553ac0)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:195 +0x66
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc0000b0240, 0xc0000b0300)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:171 +0xf4
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:157 +0x148

INFO: 2021/02/25 10:24:21 parse_demo.go:1610: Parsed %s /Volumes/GREY/code/csgo/data/rush-vs-durany-dust2.dem
```

**Comment by pnxenopoulos** [comment] 2021-02-26 01:26
Interesting. This is actually a different error. The error is occurring at https://github.com/pnxenopoulos/csgo/blob/master/csgo/parser/parse_demo.go#L1147, which looks like `currentGrenade.PlayerTeam = e.Base().Thrower.TeamState.ClanName()`. So, this method is returning the error `runtime error: invalid memory address or nil pointer dereference`. Resolving this will take some more inspection. Have you tried loading the demo in the game and seeing if there's anything weird about it? Sometimes errors crop up with players disconnect and such.

**Comment by askvrtsv** [comment] 2021-03-04 11:15
I asked a friend to watch a demo in the game. This is what he found:

> From what I saw there were some connection issues in the beginning that might have disconnected and restarted a round and also the score board was not recording rounds correctly.

I'm not familiar with Go, maybe it has constructs that allow to ignore such situations (like try/except in Python)?

**Comment by pnxenopoulos** [comment] 2021-04-06 02:32
Hey @askvrtsv, I just ran the most recent parser code on this demofile today and it worked. Can you confirm that the new code also works?

**Comment by askvrtsv** [comment] 2021-04-10 08:45
Sorry, but I was unable to parse this demo. I got a similar error again:

```
INFO: 2021/04/10 11:41:49 parse_demo.go:646: Started demoparser
INFO: 2021/04/10 11:41:49 parse_demo.go:670: Parsed arguments, reading in /Volumes/GREY/code/csgo/demos/rush-vs-durany-dust2.dem and a parse rate of 128 
INFO: 2021/04/10 11:41:50 parse_demo.go:692: Parsed demo header and mesh for map de_dust2 
INFO: 2021/04/10 11:41:50 parse_demo.go:725: Demo is of type GOTV Demo with tickrate 128 
INFO: 2021/04/10 11:41:50 parse_demo.go:726: Demo name is rush-vs-durany-dust2 from /Volumes/GREY/code/csgo/demos/rush-vs-durany-dust2.dem
INFO: 2021/04/10 11:41:50 parse_demo.go:727: Registering event handlers, parsing demo
ERROR: 2021/04/10 11:41:50 parse_demo.go:1827: DEMO STREAM ERROR
WARNING: 2021/04/10 11:41:50 parse_demo.go:1828: Demo stream errors can still write output, check for JSON file
ERROR: 2021/04/10 11:41:50 parse_demo.go:1829: runtime error: invalid memory address or nil pointer dereference
stacktrace:
goroutine 18 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.8/libexec/src/runtime/debug/stack.go:24 +0x9f
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.NewParserWithConfig.func1(0x14bc140, 0xc0004b26e0)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.6.0/pkg/demoinfocs/parser.go:315 +0x2f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1(0xc0000b0240)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:190 +0x6b
panic(0x14bc140, 0xc0004b26e0)
	/usr/local/Cellar/go/1.15.8/libexec/src/runtime/panic.go:969 +0x1b9
github.com/markus-wa/godispatch.callConsumerCode.func1()
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:120 +0x88
panic(0x14bc140, 0xc0004b26d0)
	/usr/local/Cellar/go/1.15.8/libexec/src/runtime/panic.go:969 +0x1b9
github.com/markus-wa/godispatch.callConsumerCode.func1()
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:120 +0x88
panic(0x1498bc0, 0x189a7a0)
	/usr/local/Cellar/go/1.15.8/libexec/src/runtime/panic.go:969 +0x1b9
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs/common.(*TeamState).ClanName(...)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.6.0/pkg/demoinfocs/common/common.go:143
main.main.func10(0x33b7088, 0xc000075ac0)
	/Volumes/GREY/code/csgo/csgo/parser/parse_demo.go:1205 +0x2c8
reflect.Value.call(0x1478e60, 0xc000074100, 0x13, 0x1518b25, 0x4, 0xc00146b978, 0x1, 0x1, 0xc0000fd680, 0x0, ...)
	/usr/local/Cellar/go/1.15.8/libexec/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0x1478e60, 0xc000074100, 0x13, 0xc00146b978, 0x1, 0x1, 0xc0000aaca8, 0x627d1ef73fea3801, 0x6200000003010106)
	/usr/local/Cellar/go/1.15.8/libexec/src/reflect/value.go:337 +0xb9
github.com/markus-wa/godispatch.callConsumerCode(0x1478e60, 0xc000074100, 0x13, 0xc00146b978, 0x1, 0x1)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:123 +0x8c
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0000b02a0, 0x14b2640, 0xc000075ac0)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:109 +0x252
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.gameEventHandler.dispatch(...)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.6.0/pkg/demoinfocs/game_events.go:60
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.gameEventHandler.smokeGrenadeExpired(0xc0000da9a0, 0x0, 0xc000091170, 0xc0000911a0, 0xc001cfe0f0)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.6.0/pkg/demoinfocs/game_events.go:464 +0x152
github.com/markus-wa/demoinfocs-golang/v2/pkg/demoinfocs.(*parser).handleGameEvent(0xc0000da9a0, 0xc000b03a40)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v2@v2.6.0/pkg/demoinfocs/game_events.go:39 +0x182
reflect.Value.call(0x1478860, 0xc00008e610, 0x13, 0x1518b25, 0x4, 0xc00146bf28, 0x1, 0x1, 0xc0000fc480, 0x0, ...)
	/usr/local/Cellar/go/1.15.8/libexec/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0x1478860, 0xc00008e610, 0x13, 0xc00146bf28, 0x1, 0x1, 0xc0000aaf28, 0xa5cbbc7ca57dbc01, 0xa500000007010106)
	/usr/local/Cellar/go/1.15.8/libexec/src/reflect/value.go:337 +0xb9
github.com/markus-wa/godispatch.callConsumerCode(0x1478860, 0xc00008e610, 0x13, 0xc00146bf28, 0x1, 0x1)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:123 +0x8c
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0000b0240, 0x14f9d00, 0xc000b03a40)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:109 +0x252
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc0000b0240, 0x14f9d00, 0xc000b03a40)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:195 +0x66
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc0000b0240, 0xc0000b0300)
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:171 +0xf4
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues
	/Users/ask/.local/go/pkg/mod/github.com/markus-wa/godispatch@v1.3.0/dispatch.go:157 +0x148

INFO: 2021/04/10 11:41:50 parse_demo.go:1697: Parsed %s /Volumes/GREY/code/csgo/demos/rush-vs-durany-dust2.dem
```

**Comment by pnxenopoulos** [comment] 2021-04-14 03:42
Hey @askvrtsv -- I made a substantial update. I believe this should cover a lot of the oddities we are seeing with incomplete parses. The new code worked on both the demofiles you referenced. Let me know if you run into more difficulties.

**Closed by pnxenopoulos** 2021-04-14 03:42 UTC
